version: '3.7'
volumes:
  /app/aide/v3/docker/volumes/db_data:
    name: aidev3_db_data
  /app/aide/v3/docker/volumes/images:
    name: aidev3_images
services:
  aidev3_app:
    hostname: 'aidev3_app_host'
    container_name: 'aide${AIDE_VERSION}'
    build:
      context:  '..'
      dockerfile: 'docker/Dockerfile'
    image: 'aidev3_app:aide${AIDE_VERSION}'
    volumes:
      - /app/aide/v3/docker/volumes/db_data:/var/lib/postgresql/10/main
      - /app/aide/v3/docker/volumes/images:/home/aide/images
      - ..:/home/aide/app:cached
    ports:
      - '8080:8080'
    environment:
      - AIDE_ENV=${AIDE_ENV}
      - AIDE_VERSION=${AIDE_VERSION}
