/*
    Template used to initialize a new schema in the course of
    creating a new project.
    Requires substitutions for identifiers and annotation/prediction
    type fields.

    2019-21 Benjamin Kellenberger
*/


/* base schema */
CREATE SCHEMA {id_schema}
    AUTHORIZATION {id_auth};


/* base tables */
CREATE TABLE IF NOT EXISTS {id_image} (      
    id uuid DEFAULT uuid_generate_v4(),
    filename VARCHAR UNIQUE NOT NULL,
    corrupt BOOLEAN,
    isGoldenQuestion BOOLEAN NOT NULL DEFAULT FALSE,
    --exif VARCHAR,
    --fVec bytea,
    date_added TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_requested TIMESTAMPTZ,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS {id_iu} (
    username VARCHAR NOT NULL,
    image uuid NOT NULL,
    viewcount SMALLINT DEFAULT 1,
    first_checked TIMESTAMPTZ,
    last_checked TIMESTAMPTZ,
    last_time_required BIGINT,
    total_time_required BIGINT,
    num_interactions INTEGER NOT NULL DEFAULT 0,
    meta VARCHAR,

    PRIMARY KEY (username, image),
    FOREIGN KEY (username) REFERENCES aide_admin.user(name),
    FOREIGN KEY (image) REFERENCES {id_image}(id)
);

CREATE TABLE IF NOT EXISTS {id_bookmark} (
    username VARCHAR NOT NULL,
    image uuid NOT NULL,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (username, image),
    FOREIGN KEY (username) REFERENCES "aide_admin".user(name),
    FOREIGN KEY (image) REFERENCES {id_image}(id)
);

CREATE TABLE IF NOT EXISTS {id_labelclassGroup} (
    id uuid DEFAULT uuid_generate_v4(),
    name VARCHAR NOT NULL,
    color VARCHAR,
    parent uuid,
    PRIMARY KEY (id)
);

-- https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/master/API-coleo.md
-- https://data.canadensys.net/vascan/search
-- timescale db; insert only; ON CONFLICT DO NOTHING
CREATE TABLE IF NOT EXISTS {id_labelclass} (
    id uuid DEFAULT uuid_generate_v4(),
    name VARCHAR NOT NULL,
    idx SERIAL UNIQUE NOT NULL,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    color VARCHAR DEFAULT '#095797',
    labelclassgroup uuid,
    keystroke SMALLINT UNIQUE,
    hidden BOOLEAN NOT NULL DEFAULT FALSE,
    vascan_id INT NOT NULL,
    bryoquel_id INT DEFAULT NULL,
    coleo_vernacular_fr VARCHAR DEFAULT NULL,
    coleo_vernacular_en VARCHAR DEFAULT NULL,
    vascan_region VARCHAR NOT NULL DEFAULT 'Central',
    vascan_province VARCHAR NOT NULL DEFAULT 'Québec',
    vascan_port VARCHAR DEFAULT NULL,
    vascan_statut_repartition VARCHAR DEFAULT NULL,
    tsn INT DEFAULT NULL,
    coleo_category VARCHAR NOT NULL DEFAULT 'plantes',
    PRIMARY KEY (id),
    FOREIGN KEY (labelclassgroup) REFERENCES {id_labelclassGroup}(id)
);
CREATE UNIQUE INDEX labelclass_idx
ON {id_labelclass} (name, vascan_id, coleo_vernacular_fr, coleo_vernacular_en, vascan_region, vascan_province, vascan_port, vascan_statut_repartition, coleo_category);
ALTER TABLE {id_labelclass}
ADD CONSTRAINT uniq_labelclass
UNIQUE USING INDEX labelclass_idx;

CREATE OR REPLACE VIEW {id_active_labelclass} AS
	SELECT distinct on (lc.name) lc.*
	FROM {id_labelclass} lc
	INNER JOIN {id_labelclass} lc_inner ON lc_inner.id = lc.id
	ORDER BY lc.name, lc.timeCreated DESC;

COMMENT ON COLUMN {id_labelclass}.id IS 'labelclass is the AIDE internal UUID of the label; the image/tile refer to it; autogenerated, not null; part of the original AIDE schema; i.e: "27e2ceb3-449c-11ec-a197-fa163e42617b"';
COMMENT ON COLUMN {id_labelclass}.name IS 'name is the VASCAN "Nom scientifique"; string, not null; part of the original AIDE schema; i.e. "Abies balsamea"';
COMMENT ON COLUMN {id_labelclass}.idx IS 'idx is the index of the record in the table; autogenerated, postgreSQL SERIAL type (integer), unique, not null, starting from  1; part of the original AIDE schema; i.e. "326"';
COMMENT ON COLUMN {id_labelclass}.timeCreated IS 'timeCreated is the timestamp, with the timezone, when the record has been inserted; not null, postgreSQL TIMESTAMPTZ type; part of the original AIDE schema; i.e. "2021-11-13 11:10:18.759 -0500"';
COMMENT ON COLUMN {id_labelclass}.color IS 'color is the background color of the label when it is selected in the AIDE interface; string representing the hexadecimal value of the color; can be null in which case the AIDE interface will define a value, default is "#095797"; part of the original AIDE schema;';
COMMENT ON COLUMN {id_labelclass}.labelclassgroup IS 'labelclassgroup contains the reference of the label group it belongs, if any; postgreSQL type is UUID, can be null if not part of a group; part of the original AIDE schema; i.e: "27e2ceb2-449c-11ec-a197-fa163e42617b"';
COMMENT ON COLUMN {id_labelclass}.keystroke IS 'keystroke is the keyboard shortkey that can be used to annotate using the keyboard instead of the mouse; integer value, can be null, but must be unique; part of the original AIDE schema; i.e. "7"';
COMMENT ON COLUMN {id_labelclass}.hidden IS 'hidden is a flag that show or hide the label in the AIDE interface; boolean, default is FALSE; part of the original AIDE schema; i.e. "FALSE"';
COMMENT ON COLUMN {id_labelclass}.vascan_id IS 'vascan_id is the reference to the VASCAN database ID associated with the VASCAN "Nom scientifique" and the other VASCAN columns of this table; AI model refers to it to train and classify the images/tiles; refer to https://data.canadensys.net/vascan/search; integer, not null; source: imported from the Excel document "BdQc_SP_communes_CL_2021-05-18.xlsx", provided by the MELCC; not part of the original AIDE schema, it has been added for the MELCC; i.e: "5482"';
COMMENT ON COLUMN {id_labelclass}.bryoquel_id IS 'bryoquel_id is the reference to the Bryoquel id for the bryphytes, based on the definition on "https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/master/API-coleo.md"; integer, can be null, default to NULL; not part of the original AIDE schema, it has been added for the MELCC; source: no value imported, no known data source; no known example';
COMMENT ON COLUMN {id_labelclass}.coleo_vernacular_fr IS 'coleo_vernacular_fr is the VASCAN "Nom vernaculaire français de l espèce"; string, can be null, default to NULL; source: imported from the Excel document "BdQc_SP_communes_CL_2021-05-18.xlsx", provided by the MELCC; refer to "https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/master/API-coleo.md"; not part of the original AIDE schema, it has been added for the MELCC; i.e: "achillée de Sibérie"';
COMMENT ON COLUMN {id_labelclass}.coleo_vernacular_en IS 'coleo_vernacular_en is the VASCAN "Nom vernaculaire anglais de l espèce"; string, can be null, default to NULL; source: imported from the Excel document "BdQc_SP_communes_CL_2021-05-18.xlsx", provided by the MELCC; refer to "https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/master/API-coleo.md"; not part of the original AIDE schema, it has been added for the MELCC; i.e: "Siberian yarrow"';
COMMENT ON COLUMN {id_labelclass}.vascan_region IS 'vascan_region is the VASCAN canadian region; string, not null, default "Central"; source: none, no value imported, defaulted to "Central" as AIDE+MELCC is for the Québec province; refer to https://data.canadensys.net/vascan/search; not part of the original AIDE schema, it has been added for the MELCC; i.e: "Central"';
COMMENT ON COLUMN {id_labelclass}.vascan_province IS 'vascan_province is the VASCAN canadian province; string, not null, default "Québec"; source: none, no value imported, defaulted to "Québec" as AIDE+MELCC is for the Québec province; refer to https://data.canadensys.net/vascan/search; not part of the original AIDE schema, it has been added for the MELCC; i.e: "Québec"';
COMMENT ON COLUMN {id_labelclass}.vascan_port IS 'vascan_port is the VASCAN "port???? (TODO: clarify)"; string, can be  null, default to NULL; source: imported from the Excel document "BdQc_SP_communes_CL_2021-05-18.xlsx", provided by the MELCC; refer to https://data.canadensys.net/vascan/search; not part of the original AIDE schema, it has been added for the MELCC; i.e: "Plante herbacée"';
COMMENT ON COLUMN {id_labelclass}.vascan_statut_repartition IS 'vascan_statut_repartition is the VASCAN statut repartition; string, can be null, default to NULL; source: imported from the Excel document "BdQc_SP_communes_CL_2021-05-18.xlsx", provided by the MELCC; refer to https://data.canadensys.net/vascan/search; not part of the original AIDE schema, it has been added for the MELCC; i.e: "Indigène"';
COMMENT ON COLUMN {id_labelclass}.tsn IS 'tsn is the TSN ID ("Identifiant ITS") as defined in "https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/master/API-coleo.md"; integer, can be null, default to NULL; source: none, no value imported, defaulted to NULL; not part of the original AIDE schema, it has been added for the MELCC; no known example';
COMMENT ON COLUMN {id_labelclass}.coleo_category IS 'coleo_category is the category found in the Colea database, as defined in "https://github.com/ReseauBiodiversiteQuebec/Coleo_DB/blob/master/API-coleo.md"; string, can be null, default to "plantes"; source: none, no value imported, defaulted to "plantes" as AIDE+MELCC is focussed on biodiversity; not part of the original AIDE schema, it has been added for the MELCC; refer to the Coleo_DB URL for the other possible values';


CREATE TABLE IF NOT EXISTS {id_annotation} (
    id uuid DEFAULT uuid_generate_v4(),
    username VARCHAR NOT NULL,
    image uuid NOT NULL,
    meta VARCHAR,
    autoConverted boolean,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    timeRequired BIGINT,
    unsure boolean NOT NULL DEFAULT false,
    {annotation_fields},
    PRIMARY KEY (id),
    FOREIGN KEY (username) REFERENCES aide_admin.user(name),
    FOREIGN KEY (image) REFERENCES {id_image}(id)
);

CREATE TABLE IF NOT EXISTS {id_cnnstate} (
    id uuid DEFAULT uuid_generate_v4(),
    model_library VARCHAR,
    alCriterion_library VARCHAR,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    stateDict bytea,
    stats VARCHAR,
    partial BOOLEAN NOT NULL,
    imported_from_marketplace BOOLEAN NOT NULL DEFAULT FALSE,
    marketplace_origin_id UUID,
    labelclass_autoupdate BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    FOREIGN KEY (marketplace_origin_id) REFERENCES aide_admin.modelMarketplace(id)
);

CREATE TABLE IF NOT EXISTS {id_modellc} (
    --ai_model_library VARCHAR NOT NULL,
    marketplace_origin_id UUID NOT NULL,
    labelclass_id_model VARCHAR NOT NULL,
    labelclass_name_model VARCHAR NOT NULL,
    labelclass_id_project UUID,
    PRIMARY KEY (marketplace_origin_id, labelclass_id_model),
    FOREIGN KEY (labelclass_id_project) REFERENCES {id_labelclass} (id)
);

CREATE TABLE IF NOT EXISTS {id_prediction} (
    id uuid DEFAULT uuid_generate_v4(),
    image uuid NOT NULL,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cnnstate UUID,
    confidence real,
    {prediction_fields},
    priority real,
    PRIMARY KEY (id),
    FOREIGN KEY (image) REFERENCES {id_image}(id),
    FOREIGN KEY (cnnstate) REFERENCES {id_cnnstate}(id)
);
CREATE INDEX pred_idx ON {id_prediction} (cnnstate);

CREATE TABLE IF NOT EXISTS {id_workflow} (
    id uuid DEFAULT uuid_generate_v4(),
    name VARCHAR UNIQUE,
    workflow VARCHAR NOT NULL,
    username VARCHAR NOT NULL,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    timeModified TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id),
    FOREIGN KEY (username) REFERENCES aide_admin.user(name)
);

CREATE TABLE IF NOT EXISTS {id_workflowHistory} (
    id uuid DEFAULT uuid_generate_v4(),
    workflow VARCHAR NOT NULL,
    tasks VARCHAR,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    timeFinished TIMESTAMPTZ,
    launchedBy VARCHAR,
    abortedBy VARCHAR,
    succeeded BOOLEAN,
    messages VARCHAR,
    PRIMARY KEY (id),
    FOREIGN KEY (launchedBy) REFERENCES aide_admin.user (name),
    FOREIGN KEY (abortedBy) REFERENCES aide_admin.user (name)
);

CREATE OR REPLACE VIEW {id_filehierarchy} AS (
    SELECT DISTINCT
    CASE WHEN position('/' IN filename) = 0 THEN null
    ELSE left(filename, strposrev(filename, '/')-1) END
    AS folder
    FROM {id_image}
);

/* task history */
CREATE TABLE IF NOT EXISTS {id_taskHistory} (
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    task_id uuid NOT NULL,
    launchedBy VARCHAR,
    abortedBy VARCHAR,
    processDescription VARCHAR,
    timeCreated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    timeFinished TIMESTAMPTZ,
    result VARCHAR,
    PRIMARY KEY (id),
    FOREIGN KEY (launchedBy) REFERENCES aide_admin.user (name),
    FOREIGN KEY (abortedBy) REFERENCES aide_admin.user (name)
);

CREATE TABLE IF NOT EXISTS {id_annotation_label}
(
    annotation uuid NOT NULL,
    label uuid NOT NULL,
    PRIMARY KEY (annotation, label),
    FOREIGN KEY (label) REFERENCES {id_labelclass} (id),
    FOREIGN KEY (annotation) REFERENCES {id_annotation} (id)
)

-- C:\Program Files\pgAdmin 4\v5\runtime\pg_dump.exe --file "C:\\Users\\VINCEN~1.LE_\\DOWNLO~1\\LABELC~1.DUM" --host "206.12.94.82" --port "17685" --username "ailabeluser" --no-password --verbose --quote-all-identifiers --role "ailabeluser" --format=p --data-only --inserts --column-inserts --encoding "UTF8" --table "test.labelclass" "ailabeltooldb"
-- C:\Program Files\pgAdmin 4\v5\runtime\pg_dump.exe --file "C:\\Users\\VINCEN~1.LE_\\DOWNLO~1\\LABELC~1.SQL" --host "206.12.94.82" --port "17685" --username "ailabeluser" --no-password --verbose --quote-all-identifiers --role "ailabeluser" --format=p --data-only --inserts --column-inserts --encoding "UTF8" --table "test.labelclassgroup" "ailabeltooldb"